# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-10 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.get_for_model(User)
    db_alias = schema_editor.connection.alias

    Permission.objects.using(db_alias).bulk_create([
        Permission(
            codename='client',
            name='Can create certain submissions and logout.',
            content_type=content_type),
        Permission(
            codename='staff',
            name=('Makes sure all the data the clients \
            make is formatted and used correctly.'),
            content_type=content_type),
        Permission(
            codename='admin',
            name='Can create staff and administor the database.',
            content_type=content_type),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraUserField',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('address', models.CharField(
                    max_length=254)),
                ('city', models.CharField(
                    max_length=254)),
                ('country', models.CharField(
                    max_length=254)),
                ('postalcode', models.CharField(
                    max_length=254)),
                ('hours_per_week', models.DecimalField(
                    decimal_places=2,
                    max_digits=254)),
                ('price', models.DecimalField(
                    decimal_places=2,
                    max_digits=254)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.RunPython(forwards_func),
    ]
