# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserfield',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='extrauserfield',
            name='city',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='extrauserfield',
            name='country',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='extrauserfield',
            name='hours_per_week',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=254,
                null=True),
        ),
        migrations.AlterField(
            model_name='extrauserfield',
            name='postalcode',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='extrauserfield',
            name='price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=254,
                null=True),
        ),
    ]
