# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 06:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180410_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserfield',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
