# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180411_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrauserfield',
            name='hours_per_week',
        ),
        migrations.RemoveField(
            model_name='extrauserfield',
            name='price',
        ),
    ]
