# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180411_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauserfield',
            name='token',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
