# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 08:53
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_websitestyle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitestyle',
            name='button_gradient',
        ),
        migrations.AddField(
            model_name='websitestyle',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True),
        ),
    ]
