# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180425_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitestyle',
            name='template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.WebsiteStyle'),
        ),
    ]
