# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-02 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_websitestyle_template_css_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitestyle',
            name='save_template',
            field=models.BooleanField(
                default=False,
                help_text='Do you want to save the template? Yes / No'),
        ),
        migrations.AlterField(
            model_name='websitestyle',
            name='template',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'Select one of the templates you want to use.' +
                    'You can also choose not to select any template.'),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.WebsiteStyle'),
        ),
        migrations.AlterField(
            model_name='websitestyle',
            name='template_name',
            field=models.CharField(
                blank=True,
                help_text='Set a templatename for the template.',
                max_length=255,
                null=True,
                unique=True),
        ),
    ]
