# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-03 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20180502_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('log_action', models.CharField(
                    blank=True,
                    max_length=255,
                    null=True)),
                ('log', models.TextField()),
                ('user', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='websitestyle',
            name='template',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'Select one of the templates you want' +
                    ' to use.You can also choose not to select any template.'),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.WebsiteStyle'),
        ),
    ]
