# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-03 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180503_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
